import { emailApiRoutes } from './emailApiRoutes';

export const ApiRoutes = {
	...emailApiRoutes,
	validateUser: 'validate-user',
	usersAccepted: 'workspace/:id/users/accepted',
	validateWorkspace: 'validate/workspace',
	createWorkspace: 'workspace',
	createUser: 'create-user',
	updateTenant: 'workspace',
	datasetList: 'workspace/:id/dataset',
	registerDeviceFcmToken: 'register-device-fcmToken',
	deactiveDeviceFcmToken: 'deactivate-device-fcmToken',
	editDataset: 'workspace/:id/dataset/:datasetId',
	createGroupData: 'workspace/:id/dataset/group',
	moveWork: 'workspace/:workspaceId/dataset/move/work',
	deleteGroup: 'workspace/:id/dataset/group/:groupId',
	renameGroup: 'workspace/:workspaceId/dataset/group/:groupId',
	datasetGroupByTemplate: 'workspace/:id/dataset/template/group',
	createDataset: 'workspace/:workspaceId/dataset',
	createQuickRecord: 'workspace/:workspaceId/datasets/quick/add',
	customizationField: 'workspace/:workspaceId/customize/fields',
	getAllDatastesList: 'workspace/:workspaceId/customize/fields/all',
	datasetRecordList: 'workspace/:id/datasets/:dataset/list',
	deleteDatasetTypes: 'workspace/:id/datasets/:dataset',
	listPageSelectedColumn: 'workspace/:id/columns',
	updateFieldWidth: 'workspace/:id/columns/field-width',
	sortField: 'workspace/:id/columns/field-sort',
	updateStage: 'workspace/:id/datasets/:dataset/board/:recordId',
	getUserListBasedOnRole: 'workspace/:workspaceId/users',
	updateRecordFieldValue: 'workspace/:workspaceId/datasets/:datasetId/:fieldId/fields',
	updateStageReorder: 'workspace/:workspaceId/datasets/:datasetName/stage/reorder/:stageId',
	updateStageList: 'workspace/:workspaceId/stage/:datasetName',
	recordBasicInfo: 'workspace/:id/basic-info/:workId/:type/:rid',
	createAndUpdateNote: 'workspace/:workspaceId/activity/note',
	fieldUpdate: 'workspace/:id/field/:fieldId',
	editField: 'workspace/:id/field/customization/:fieldId',
	fieldList: 'workspace/:id/field',
	deleteField: 'workspace/:id/field/:fieldId',
	fieldDetailList: 'workspace/:id/table-settings',
	datasetRelation: 'workspace/:workspaceId/dataset/relation',
	deleteDatasetRelation: 'workspace/:workspaceId/dataset/relation/:datasetId',
	multipleDatasetsRelation: 'workspace/:workspaceId/dataset/relations',
	preSignedMultipleUrl: 'workspace/:id/upload/pre-signed-multiple',
	deleteDataSetFiles:
		'workspace/:workspaceId/datasets/:datasetName/:datasetId/record/:recordId/file/:fieldName/:fileId',
	customizeField: 'workspace/:worspaceId/customize/selected?type=:type',
	groupList: 'workspace/:workspaceId/group',
	groupUpdateList: 'workspace/:workspaceId/group/order',
	roleList: 'workspace/:id/roles',
	addRole: 'workspace/:id/role',
	cloneRole: 'workspace/:id/role/clone/:roleId',
	editRole: 'workspace/:id/role/:roleId',
	updateUserProfile: 'workspace/:id/profile/:userId',
	updateUserProfilePicture: 'workspace/:id/profile/picture/:userId',
	changeWorkspace: 'workspace/default',
	addWorkspace: 'workspace/add',
	editWorkspace: 'workspace/rename',
	deleteWorkspace: 'workspace/:workspaceId/:wName',
	workspace: 'workspace',
	organisationWorkspace: 'workspace/:orgId',
	addBoard: 'workspace/:workspaceId/board',
	datasets: 'workspace/:id/datasets',
	deleteDataset: 'workspace/:workspaceId/dataset/:datasetId',
	userList: 'users/:orgId',
	usersWorkspaceBasedList: 'users/workspace/:workspaceId',
	userInvite: 'user/invite',
	resendUserInvite: 'user/invite/resend/:id',
	team: 'team',
	editTeam: 'team/:id',
	deleteTeam: 'team/:id',
	workspaceRoleList: 'role/:userId/workspace',
	validateEmail: 'user/validate/email',
	addUsers: 'workspace/users/add',
	editUser: 'user/:userId',
	deleteUser: 'user/:id/remove',
	deactivateUser: 'user/:id/deactivate',
	activateUser: 'user/:id/activate',
	editRecord: 'workspace/:id/datasets/:recordId',
	addRecordFields: 'workspace/:id/add',
	editRecordFields: 'workspace/:id/edit',
	associateWith: 'workspace/:id/associate',
	datasetAssociate: 'workspace/:id/associate',
	personDatasetSearch: 'workspace/:id/dataset/search-user',
	createField: 'workspace/:workspaceId/field',
	userOrganisation: 'user/organisation',
	taskList: 'workspace/:workspaceId/datasets/:datasetId/:datasetName/engagement/task',
	taskIsCompleted:
		'workspace/:workspaceId/datasets/:datasetId/:datasetName/engagement/task/task-isCompleted',
	meetingList: 'workspace/:workspaceId/datasets/:datasetId/:datasetName/engagement/meeting',
	overview: 'workspace/:workspaceId/datasets/:datasetName/engagement/overview',
	note: 'workspace/:workspaceId/datasets/:datasetId/:datasetName/engagement/notes',
	recordActivity: 'workspace/:workspaceId/datasets/:datasetId/:datasetName/record-activitys',
	recordActivityCount:
		'workspace/:workspaceId/datasets/:datasetId/:datasetName/record-activitys/count',
	linkStageToDataset: 'workspace/:id/datasets/:datasetName/board/stage',
	stageList: 'workspace/:workspaceId/datasets/:datasetName/board/stage/:stageId',
	commentList: 'workspace/:workspaceId/comment',
	googleConnectionUrl: 'integration/google',
	updateDatasetSettings: 'workspace/:workspaceId/dataset/settings/:datasetId',
	fileList: 'workspace/:workspaceId/datasets/:datasetName/:datasetId/engagement/files',
	boardList: 'workspace/:workspaceId/board/:datasetId',
	userMultipleInvite: 'user/mul-invite',
	datasetAccess: 'workspace/:workspaceId/getAccess/:workId/:recordId',
	getAllNotification: 'all/:userId',
	markAllAsRead: 'markRead/:userId',
	getNotificationBadgeCount: 'count/:userId',
};
