export const Constants = {
  accesToken: "accessToken",
  refreshToken: "refreshToken",
  workspaceId: "workspaceId",
  userManagement: {
    user: "user",
    team: "team",
    role: "role",
  },
  FieldTypes: {
    SingleLine: "single-line",
    MultiLine: "multi-line",
    DropDown: "drop-down",
    MultiSelect: "multi-select",
    Number: "number",
    Currency: "currency",
    DatePicker: "date-picker",
    Priority: "priority",
    Email: "email",
    Website: "website",
    PhoneNumber: "phone-number",
    User: "user",
    Collaborators: "collaborators",
    files: "file",
  },
  dataFields: {
    field: "field",
    group: "group",
    object: "object",
  },
  columnKeys: {
    associatedContact: "associated_contact",
  },
  actions: {
    delete: "delete",
    edit: "edit",
    deleteUser: "deleteUser",
    editUser: "editUser",
    deleteRole: "deleteRole",
    editRole: "editRole",
    deleteTeam: "deleteTeam",
    editTeam: "editTeam",
    deleteGroup: "deleteGroup",
    editGroup: "editGroup",
    editField: "editField",
    resendInvite: "resendInvite",
    makeSuperAdmin: "makeSuperAdmin",
    viewFields: "viewFields",
    moveToGroup: "moveToGroup",
    copyInternalName: "copyInternalName",
    deleteEmailTemplate: "deleteEmailTemplate",
    cloneEmailTemplate: "cloneEmailTemplate",
    archive: "archive",
    unarchive: "unarchive",
    deleteFromUnarchive: "deleteFromUnarchive",
  },
  sideSettingsTabValue: {
    Personal: 1,
    FieldAndCustomization: 2,
    Email: 3,
    UserManagement: 4,
    Integration: 5,
  },
  tabCompValue: {
    properties: {
      DataFields: 0,
      Customization: 1,
    },
  },
  tabStateValues: {
    dealCustomizationState: "2",
  },
  activity: {
    task: "TASK",
    appointment: "APPOINTMENT",
  },
  detailList: {
    leadOwner: "lead_owner",
    contactOwner: "contact_owner",
    companyOwner: "company_owner",
    companyName: "company_name",
    dealOwner: "deal_owner",
    mailId: "mail_id",
    closingDate: "closing_date",
    contactStage: "contact_stage",
    stage: "stage",
    user: "user",
    priority: "priority",
  },
  detailFieldTypes: ["drop-down", "multi-select", "date-picker"],
  settings: {
    addRoleText: "addRole",
    customRole: "Custom Role",
    activity: "Activity",
    account: "account",
    customization: "Customization",
    dealsAandCustomization: ["customization", "properties"],
    objectTypeList: ["Deals", "Companies", "Contacts"],
    dataFieldsList: ["field", "group", "customobjects"],
    objectDetails: {
      CompanyLike: "CompanyLike",
      ConactLike: "ContactLike",
      DealLike: "DealLike",
    },
    objectType: {
      deals: "Deals",
      companies: "Companies",
      contacts: "Contacts",
      actions: {
        add: "Add",
        edit: "Edit",
        bulkEdit: "Bulk-Edit",
      },
    },
    company: "Company",
    relationshipList: [
      {
        label: "One to One",
        value: "1",
      },
      {
        label: "One to Many",
        value: "2",
      },
    ],

    objectTypeListOfObject: [
      {
        label: "Deals",
        value: "deals",
      },
      {
        label: "Companies",
        value: "companies",
      },
      {
        label: "Contacts",
        value: "contacts",
      },
    ],

    contactObjectTypeList: ["Companies", "Contacts"],
    dealsObjectTypeList: ["Deals"],
    fieldTypeList: [
      { key: "single-line", label: "Single-line text" },
      { key: "multi-line", label: "Multi-line text" },
      { key: "number", label: "Number" },
      { key: "currency", label: "Currency" },
      { key: "drop-down", label: "Dropdown" },
      { key: "multi-select", label: "Multi select" },
      { key: "date-picker", label: "Date picker" },
      { key: "priority", label: "Priority" },
    ],
    fieldTypeReplaceData: {
      "single-line": "Single-line text",
      "multi-line": "Multi-line text",
      number: "Number",
      currency: "Currency",
      "drop-down": "Dropdown",
      "multi-select": "Multi select",
      "date-picker": "Date picker",
      user: "User",
      priority: "Priority",
      file: "File",
    },
    menuHeaderList: {
      menuData: [
        { name: "headername" },
        { name: "settings", value: "Settings", testId: "settings-btn" },
        {
          name: "privacyPolicy",
          value: "Privacy Policy",
          testId: "policy-btn",
        },
        { name: "signOut", value: "Sign Out", testId: "logout-btn" },
      ],
      dashBoardData: [
        { id: "header-dashboard", name: "Dashboard", key: "dashboard" },
        { id: "activities", name: "Activities", key: "activities" },
        { id: "header-contacts", name: "Contacts", key: "contacts" },
        { id: "header-companies", name: "Companies", key: "companies" },
        { id: "header-deal", name: "Deals", key: "deals" },
        { id: "header-report", name: "Report", key: "report" },
      ],
      languagesList: [
        { id: "en", value: "English", content: "Welcome to CRM" },
        { id: "fr", value: "Française", content: "Bienvenue dans le CRM" },
        { id: "tm", value: "தமிழ்", content: "சி.ஆர்.எம் உங்களை வரவேற்கிறது" },
        { id: "es", value: "Española", content: "Bienvenida a CRM" },
      ],
    },
    leads: "leads",
    deals: "deals",
    contacts: "contacts",
    companies: "companies",
    activities: "activities",
    needArrowMarkData: {
      name: "Name",
      email: "Email",
      dealName: "Deal Name",
      amount: "Amount",
      companyOwner: "Company Owner",
      title: "Title",
    },
    pageCountData: [20, 50, 75, 100],
    defaultPageLimit: 20,
    defaultPageNumber: 1,
    pageTitleList: "list",
    pageTitleBoard: "board",
    pending: "Pending",
    rejected: "rejected",
    headerData: {
      deals: ["Deal Name", "Closing Date", "Amount"],
      contacts: ["Name", "Email", "Company Name"],
      companies: ["Company Name"],
    },
    bodyData: {
      deals: ["dealName", "closingDate", "amount"],
      contacts: ["name", "email", "companyName"],
      companies: ["companyName"],
    },
    rowData: {
      deals: ["dealName", "closingDate", "amount"],
      contacts: ["name", "email", "companyName"],
      companies: ["companyName"],
    },
    pipelineOptionsData: [
      { key: "renamePipeline", value: "Rename this pipeline" },
      { key: "reorderPipeline", value: "Reorder pipelines" },
      { key: "deletePipeline", value: "Delete this pipeline" },
    ],
    dateRange: {
      startDate: "1 Jan 1900",
      endDate: "31 Dec 2099",
    },
    winProbabilityEmptyError: "Win probability must contain a numeric value",
    winProbabilityPercentageError: "Win probability must be between 1-100",
    invalidWinProbabilityErrorMsg: "Win probability must contain only numbers",
    stageNameMinMaxlengthError:
      "Stage name must contain minimum of 2 to maximum of 40 characters",
    invalidStageNameError:
      "Stage name must contain only letters, numbers, spaces and underscore",
    existingStageNameError: "Stage name already exists",
    pipelineEmptyError:
      "Pipeline name must contain minimum of 2 to maximum of 50 characters",
    invalidPipelineError:
      "Pipeline Name must contain only letters, numbers and space (a-zA-Z, 0-9)",
    existingPipelineError: "Pipeline name already exists",
    tokenExpired: "Token expired. Please login again",
    userLoggedIn: "User must be logged in",
    tryAgain: "Failed to authenticate. Please try logging again",
    wentWrong: "Something went wrong. Please try again after sometime.",
    userNotFound: "User name could not be found",
    unKnownUser: "Unknown user",
    unAuthorized:
      "Unauthorized. Please login to this workspace before proceeding.",
    task: "Task",
    appointment: "Appointment",
    note: "Note",
    completed: "completed",
    overdue: "overdue",
    upcoming: "upcoming",
    timeline: "Timeline",
    table: "Table",
    basicDetails: "basicDetails",
    addMember: "Add Member",
    contactStatus: "Contact Status",
    contactStatusCamel: "contact_stage",
    contactNameCamel: "contact_name",
    firstNameCamel: "first_name",
    contactName: "contact_name",
    name: "name",
    dealNameCamel: "deal_name",
    objectTypes: "objectTypes",
    superAdmin: "Super Admin",
    addButtonTitle: "addButtonTitle",
    editButtonTitle: "editButtonTitle",
    placeHolder: "placeHolder",
    pageTitle: "pageTitle",
    searchIdList: {
      deals: "dealEmptySearch",
      companies: "companyEmptySearch",
      contacts: "contactEmptySearch",
    },
    objectTypesList: {
      deals: "deal_name",
      companies: "company_name",
    },
    emptyDataIdList: {
      deals: "noDealFound",
      companies: "noCompanyFound",
      contacts: "noContactFound",
    },
    addColumnData: [
      "Assigned To",
      "Object Type",
      "Activity Type",
      "Associated With",
      "Due Date",
      "Meeting Date",
      "Time",
      "Attendees",
      "Created By",
    ],
    between: "between",
    isEqual: "is equal",
    empty: "empty",
    notEmpty: "not empty",
    isAfter: "is after",
    isBefore: "is before",
    contain: "contain",
    notContain: "not contain",
    is: "is",
    notEqual: "not equal",
    isGreater: "is greater",
    isLess: "is less",
    today: "today",
    yesterday: "yesterday",
    thisWeek: "this week",
    thisMonth: "this month",
  },
  languageById: {
    en: "English",
    fr: "Française",
    es: "Española",
    tm: "தமிழ்",
  },
  countryCodeByName: {
    Afghanistan: "AF",
    "Aland Islands": "AX",
    Albania: "AL",
    Algeria: "DZ",
    "American Samoa": "AS",
    Andorra: "AD",
    Angola: "AO",
    Anguilla: "AI",
    Antarctica: "AQ",
    "Antigua And Barbuda": "AG",
    Argentina: "AR",
    Armenia: "AM",
    Aruba: "AW",
    Australia: "AU",
    Austria: "AT",
    Azerbaijan: "AZ",
    Bahamas: "BS",
    Bahrain: "BH",
    Bangladesh: "BD",
    Barbados: "BB",
    Belarus: "BY",
    Belgium: "BE",
    Belize: "BZ",
    Benin: "BJ",
    Bermuda: "BM",
    Bhutan: "BT",
    Bolivia: "BO",
    "Bosnia And Herzegovina": "BA",
    Botswana: "BW",
    "Bouvet Island": "BV",
    Brazil: "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    Bulgaria: "BG",
    "Burkina Faso": "BF",
    Burundi: "BI",
    Cambodia: "KH",
    Cameroon: "CM",
    Canada: "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    Chad: "TD",
    Chile: "CL",
    China: "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    Colombia: "CO",
    Comoros: "KM",
    Congo: "CG",
    "Congo, Democratic Republic": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Cote D'Ivoire": "CI",
    Croatia: "HR",
    Cuba: "CU",
    Cyprus: "CY",
    "Czech Republic": "CZ",
    Denmark: "DK",
    Djibouti: "DJ",
    Dominica: "DM",
    "Dominican Republic": "DO",
    Ecuador: "EC",
    Egypt: "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    Eritrea: "ER",
    Estonia: "EE",
    Ethiopia: "ET",
    "Falkland Islands (Malvinas)": "FK",
    "Faroe Islands": "FO",
    Fiji: "FJ",
    Finland: "FI",
    France: "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    Gabon: "GA",
    Gambia: "GM",
    Georgia: "GE",
    Germany: "DE",
    Ghana: "GH",
    Gibraltar: "GI",
    Greece: "GR",
    Greenland: "GL",
    Grenada: "GD",
    Guadeloupe: "GP",
    Guam: "GU",
    Guatemala: "GT",
    Guernsey: "GG",
    Guinea: "GN",
    "Guinea-Bissau": "GW",
    Guyana: "GY",
    Haiti: "HT",
    "Heard Island & Mcdonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    Honduras: "HN",
    "Hong Kong": "HK",
    Hungary: "HU",
    Iceland: "IS",
    India: "IN",
    Indonesia: "ID",
    "Iran, Islamic Republic Of": "IR",
    Iraq: "IQ",
    Ireland: "IE",
    "Isle Of Man": "IM",
    Israel: "IL",
    Italy: "IT",
    Jamaica: "JM",
    Japan: "JP",
    Jersey: "JE",
    Jordan: "JO",
    Kazakhstan: "KZ",
    Kenya: "KE",
    Kiribati: "KI",
    Korea: "KR",
    Kuwait: "KW",
    Kyrgyzstan: "KG",
    "Lao People's Democratic Republic": "LA",
    Latvia: "LV",
    Lebanon: "LB",
    Lesotho: "LS",
    Liberia: "LR",
    "Libyan Arab Jamahiriya": "LY",
    Liechtenstein: "LI",
    Lithuania: "LT",
    Luxembourg: "LU",
    Macao: "MO",
    Macedonia: "MK",
    Madagascar: "MG",
    Malawi: "MW",
    Malaysia: "MY",
    Maldives: "MV",
    Mali: "ML",
    Malta: "MT",
    "Marshall Islands": "MH",
    Martinique: "MQ",
    Mauritania: "MR",
    Mauritius: "MU",
    Mayotte: "YT",
    Mexico: "MX",
    "Micronesia, Federated States Of": "FM",
    Moldova: "MD",
    Monaco: "MC",
    Mongolia: "MN",
    Montenegro: "ME",
    Montserrat: "MS",
    Morocco: "MA",
    Mozambique: "MZ",
    Myanmar: "MM",
    Namibia: "NA",
    Nauru: "NR",
    Nepal: "NP",
    Netherlands: "NL",
    "Netherlands Antilles": "AN",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    Nicaragua: "NI",
    Niger: "NE",
    Nigeria: "NG",
    Niue: "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    Norway: "NO",
    Oman: "OM",
    Pakistan: "PK",
    Palau: "PW",
    "Palestinian Territory, Occupied": "PS",
    Panama: "PA",
    "Papua New Guinea": "PG",
    Paraguay: "PY",
    Peru: "PE",
    Philippines: "PH",
    Pitcairn: "PN",
    Poland: "PL",
    Portugal: "PT",
    "Puerto Rico": "PR",
    Qatar: "QA",
    Reunion: "RE",
    Romania: "RO",
    "Russian Federation": "RU",
    Rwanda: "RW",
    "Saint Barthelemy": "BL",
    "Saint Helena": "SH",
    "Saint Kitts And Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin": "MF",
    "Saint Pierre And Miquelon": "PM",
    "Saint Vincent And Grenadines": "VC",
    Samoa: "WS",
    "San Marino": "SM",
    "Sao Tome And Principe": "ST",
    "Saudi Arabia": "SA",
    Senegal: "SN",
    Serbia: "RS",
    Seychelles: "SC",
    "Sierra Leone": "SL",
    Singapore: "SG",
    Slovakia: "SK",
    Slovenia: "SI",
    "Solomon Islands": "SB",
    Somalia: "SO",
    "South Africa": "ZA",
    "South Georgia And Sandwich Isl.": "GS",
    Spain: "ES",
    "Sri Lanka": "LK",
    Sudan: "SD",
    Suriname: "SR",
    "Svalbard And Jan Mayen": "SJ",
    Swaziland: "SZ",
    Sweden: "SE",
    Switzerland: "CH",
    "Syrian Arab Republic": "SY",
    Taiwan: "TW",
    Tajikistan: "TJ",
    Tanzania: "TZ",
    Thailand: "TH",
    "Timor-Leste": "TL",
    Togo: "TG",
    Tokelau: "TK",
    Tonga: "TO",
    "Trinidad And Tobago": "TT",
    Tunisia: "TN",
    Turkey: "TR",
    Turkmenistan: "TM",
    "Turks And Caicos Islands": "TC",
    Tuvalu: "TV",
    Uganda: "UG",
    Ukraine: "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Outlying Islands": "UM",
    Uruguay: "UY",
    Uzbekistan: "UZ",
    Vanuatu: "VU",
    Venezuela: "VE",
    "Viet Nam": "VN",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.S.": "VI",
    "Wallis And Futuna": "WF",
    "Western Sahara": "EH",
    Yemen: "YE",
    Zambia: "ZM",
    Zimbabwe: "ZW",
    "North Macedonia": "MK",
    Češka: "CZ",
  },
  timelineEventType: {
    datasetCreated: "dataset_created",
    leadCreated: "lead_created",
    contactCreated: "contact_created",
    objectCreated: "object_created",
    dealCreated: "deal_created",
    companyCreated: "company_created",
    engagementTask: "engagement_task",
    engagementAppointment: "engagement_appointment",
    engagementNote: "engagement_note",
    assignLead: "assign_lead",
    assignContact: "assign_contact",
    assignDeal: "assign_deal",
    assignCompany: "assign_company",
    leadUpgraded: "lead_upgraded",
    dealUpgraded: "deal_upgraded",
    dealWon: "deal_won",
    dealLost: "deal_lost",
    dealLostUpdated: "deal_lost_updated",
    contactToCompany: "contact_linkedto_company",
    contactToDeal: "contact_linkedto_deal",
    companyToDeal: "company_linkedto_deal",
    leadStageDeleted: "lead_stage_deleted",
    leadStageRenamed: "lead_stage_renamed",
    leadStageUpdated: "lead_stage_updated",
    leadStageReassigned: "lead_stage_reassigned",
    contactStageDeleted: "contact_stage_deleted",
    contactStageRenamed: "contact_stage_renamed",
    contactStageUpdated: "contact_stage_updated",
    contactStageReassigned: "contact_stage_reassigned",
    sampleLeadCreated: "sample_lead_created",
    dealPipelineChanged: "deal_pipeline_changed",
    sampleContactCreated: "sample_contact_created",
    sampleDealCreated: "sample_deal_created",
    sampleCompanyCreated: "sample_company_created",
    customObjCreated: "object_created",
    objectStageDelete: "object_stage_deleted",
    objectStageReassigned: "object_stage_reassigned",
    objectStageRename: "object_stage_renamed",
    objectStageAssigned: "object_stage_assigned",
    objectPipelineAssigned: "object_pipeline_assigned",
    recordAssociation: "sourceObject_linkedto_targetObject",
    recordDisAssociation: "sourceObject_unlinked_from_targetObject",
    objectWon: "object_won",
    objectLoss: "object_lost",
    objectLostReasonUpdate: "object_lost_reason_updated",
    objectLostReason: "object_lost_reason",
    objectPipelineRename: "object_pipeline_renamed",
    fieldUpdated: "field_updated",
    objectAssigned: "assign_object",
    objectReAssigned: "reassign_object",
  },
  clientId: "",
  importConstants: {
    sampleCsvFileUrl: {
      ContactLike:
        "https://calibcrm.s3.amazonaws.com/assets/sample-files/sample+Contact.csv",
      CompanyLike:
        "https://calibcrm.s3.amazonaws.com/assets/sample-files/sample+Company.csv",
    },
    maxFileSize: 100000000,
    name: "import",
    fileFormats: ["XLS", "XLSX", "CSV"],
    fieldInclude: ["includeColumn", "includeAll", "includeSelected"],
  },
  imageTypes: ["image/png", "image/jpg", "image/jpeg"],
  calendarToken: "",
  contactModules: ["contacts", "companies"],
  dateFormat: {
    withTime: "DD MMM YYYY [at] hh:mm A",
    onlyDateYear: "DD MMMM, YYYY",
  },
  dealStages: {
    lost: "Lost",
    won: "Won",
  },
  activityEvents: {
    completed: "Completed",
    overDue: "Overdue",
    open: "Open",
  },
  tooltipMessage: {
    superAdmin:
      "Super Admin is the owner of this workspace. This user cannot be edited or deleted.",
    tooltipImortMessage:
      "This permission can be enabled only when the permission to add or edit the contacts is enabled.",
    tooltipBulkEditMessage:
      "This permission can be enabled only when the permission to add or edit for contact, companies and deals is enabled.",
    emptyActivity: "No Activities are planned.",
    todayActivity: "Activities are due today.",
    futurectivity: "No Activity is due for today.",
    overDueActivity: "Activities are past due.",
  },
  monthInString: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sept",
    "Oct",
    "Nov",
    "Dec",
  ],
  daysInMonth: [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  ],
  daysInWeek: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  apiDefaultData: {
    status: false,
    code: 400,
    data: [],
    apiErrorCode: 0,
  },
  objectTypeListDefaultData: {
    status: false,
    code: 400,
    displayMessage: "",
    data: {
      contacts: [],
      deals: [],
      companies: [],
      objectType: "",
      pageCount: 0,
    },
  },
  reportListTag: [
    "Deal Won Over Time",
    "Activities",
    "Deals Started",
    "Deal Progress",
    "Deal Conversion",
  ],
  imageDataTypes: [".jpeg", ".jpg", ".png", ".svg", ".gif"],
  periodRanges: ["thisWeek", "thisMonth", "previousMonth", "thisyear", "range"],
  chartHeight: {
    dashboard: 273,
    report: 335,
  },
  exportTypes: [
    {
      key: "csv",
      value: "Export CSV",
    },
    {
      key: "xls",
      value: "Export XLS",
    },
    {
      key: "xlsx",
      value: "Export XLSX",
    },
  ],
  reportLists: {
    dealWonOverTime: "Deal Won Over Time",
    activities: "Activities",
    dealsStarted: "Deals Started",
    dealProgress: "Deal Progress",
    dealConversion: "Deal Conversion",
  },
  activityTableHeaders: {
    done: "Done",
    title: "Title",
    assignedTo: "Assigned To",
    objectType: "Object Type",
    activityType: "Activity Type",
    associatedWith: "Associated With",
    date: "Date",
    attendees: "Attendees",
    createdBy: "Created By",
    meetingDate: "Meeting Date",
    dueDate: "Due Date",
    time: "Time",
    associateWith: "Associate With",
    timeZone: "Timezone",
    guest: "Guest",
    nonGuest: "Non Guest",
  },
  report: "report",
  fieldTypes: {
    singleLine: "single-line",
    multiLine: "multi-line",
    number: "number",
    currency: "currency",
    dropDown: "drop-down",
    multiSelect: "multi-select",
    datePicker: "date-picker",
    user: "user",
    priority: "priority",
  },
  languageKey: {
    company: "company",
    deals: "deals",
    contacts: "contacts",
    task: "task",
    appointment: "appointment",
    note: "note",
    contact: "contact",
    deal: "deal",
  },
  snackBarSeverity: {
    success: "success",
    error: "error",
    info: "info",
  },
  initialTimeZone: {
    value: "Asia/Kolkata",
    label: "(GMT+5:30) Chennai, Kolkata, Mumbai, New Delhi",
    offset: 5.5,
    abbrev: "IST",
    altName: "India Standard Time",
  },
  apiResponseKeys: {
    status: "status",
    code: "code",
    data: "data",
    displayMessage: "displayMessage",
  },
  s3UploadPurpose: {
    importKey: "import",
    profile: "profile",
    email: "email",
  },
  email: {
    uploadMaxLimit: 25000000,
    acceptFormatTypes:
      ".csv, text/csv, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, image/png, .jpeg, .doc, .docx, .ppt, .pptx, .txt, image/*, text/*, .pdf",
    maximumMailContent: 200,
  },
  emailTemplateList: {
    emailTemplateList: "emailTemplateList",
  },
  drawerWidthClassNames: {
    small: "small-drawer-width",
    medium: "medium-drawer-width",
    large: "large-drawer-width",
    common: "common-drawer-width",
  },
  maximumNumberFieldLimit: 50000000000,
  emailSettings: {
    template: "emailTemplates",
    setting: "inboxSettings",
  },
  currencyFormatList: [
    { code: "AFN", label: "AFN - Afghanistan Afghanis" },
    { code: "ALL", label: "ALL - Albania Leke" },
    { code: "DZD", label: "DZD - Algeria Dinars" },
    { code: "ARS", label: "ARS - Argentina Pesos" },
    { code: "AUD", label: "AUD - Australia Dollars" },
    { code: "ATS", label: "ATS - Austria Schillings" },
    { code: "BSD", label: "BSD - Bahamas Dollars" },
    { code: "BHD", label: "BHD - Bahrain Dinars" },
    { code: "BDT", label: "BDT - Bangladesh Taka" },
    { code: "BBD", label: "BBD - Barbados Dollars" },
    { code: "BEF", label: "BEF - Belgium Francs" },
    { code: "BMD", label: "BMD - Bermuda Dollars" },
    { code: "BRL", label: "BRL - Brazil Reais" },
    { code: "BGN", label: "BGN - Bulgaria Leva" },
    { code: "CAD", label: "CAD - Canada Dollars" },
    { code: "XOF", label: "XOF - CFA BCEAO Francs" },
    { code: "XAF", label: "XAF - CFA BEAC Francs" },
    { code: "CLP", label: "CLP - Chile Pesos" },
    { code: "CNY", label: "CNY - China Yuan Renminbi" },
    { code: "COP", label: "COP - Colombia Pesos" },
    { code: "XPF", label: "XPF - CFP Francs" },
    { code: "CRC", label: "CRC - Costa Rica Colones" },
    { code: "HRK", label: "HRK - Croatia Kuna" },
    { code: "CYP", label: "CYP - Cyprus Pounds" },
    { code: "CZK", label: "CZK - Czech Republic Koruny" },
    { code: "DKK", label: "DKK - Denmark Kroner" },
    { code: "DEM", label: "DEM - Deutsche (Germany) Marks" },
    { code: "DOP", label: "DOP - Dominican Republic Pesos" },
    { code: "NLG", label: "NLG - Dutch (Netherlands) Guilders" },
    { code: "XCD", label: "XCD - Eastern Caribbean Dollars" },
    { code: "EGP", label: "EGP - Egypt Pounds" },
    { code: "EEK", label: "EEK - Estonia Krooni" },
    { code: "EUR", label: "EUR - Euro" },
    { code: "FJD", label: "FJD - Fiji Dollars" },
    { code: "FIM", label: "FIM - Finland Markkaa" },
    { code: "FRF", label: "FRF - France Francs" },
    { code: "XAU", label: "XAU - Gold Ounces" },
    { code: "GRD", label: "GRD - Greece Drachmae" },
    { code: "GTQ", label: "GTQ - Guatemalan Quetzal" },
    { code: "HKD", label: "HKD - Hong Kong Dollars" },
    { code: "HUF", label: "HUF - Hungary Forint" },
    { code: "ISK", label: "ISK - Iceland Kronur" },
    { code: "XDR", label: "XDR - IMF Special Drawing Right" },
    { code: "INR", label: "INR - India Rupees" },
    { code: "IDR", label: "IDR - Indonesia Rupiahs" },
    { code: "IRR", label: "IRR - Iran Rials" },
    { code: "IQD", label: "IQD - Iraq Dinars" },
    { code: "IEP", label: "IEP - Ireland Pounds" },
    { code: "ILS", label: "ILS - Israel New Shekels" },
    { code: "ITL", label: "ITL - Italy Lire" },
    { code: "JMD", label: "JMD - Jamaica Dollars" },
    { code: "JPY", label: "JPY - Japan Yen" },
    { code: "JOD", label: "JOD - Jordan Dinars" },
    { code: "KES", label: "KES - Kenya Shillings" },
    { code: "KRW", label: "KRW - Korea (South) Won" },
    { code: "KWD", label: "KWD - Kuwait Dinars" },
    { code: "LBP", label: "LBP - Lebanon Pounds" },
    { code: "LUF", label: "LUF - Luxembourg Francs" },
    { code: "MYR", label: "MYR - Malaysia Ringgits" },
    { code: "MTL", label: "MTL - Malta Liri" },
    { code: "MUR", label: "MUR - Mauritius Rupees" },
    { code: "MXN", label: "MXN - Mexico Pesos" },
    { code: "MAD", label: "MAD - Morocco Dirhams" },
    { code: "NZD", label: "NZD - New Zealand Dollars" },
    { code: "NOK", label: "NOK - Norway Kroner" },
    { code: "OMR", label: "OMR - Oman Rials" },
    { code: "PKR", label: "PKR - Pakistan Rupees" },
    { code: "XPD", label: "XPD - Palladium Ounces" },
    { code: "PEN", label: "PEN - Peru Nuevos Soles" },
    { code: "PHP", label: "PHP - Philippines Pesos" },
    { code: "XPT", label: "XPT - Platinum Ounces" },
    { code: "PLN", label: "PLN - Poland Zlotych" },
    { code: "PTE", label: "PTE - Portugal Escudos" },
    { code: "QAR", label: "QAR - Qatar Riyals" },
    { code: "RON", label: "RON - Romania New Lei" },
    { code: "ROL", label: "ROL - Romania Lei" },
    { code: "RUB", label: "RUB - Russia Rubles" },
    { code: "SAR", label: "SAR - Saudi Arabia Riyals" },
    { code: "XAG", label: "XAG - Silver Ounces" },
    { code: "SGD", label: "SGD - Singapore Dollars" },
    { code: "SKK", label: "SKK - Slovakia Koruny" },
    { code: "SIT", label: "SIT - Slovenia Tolars" },
    { code: "ZAR", label: "ZAR - South Africa Rand" },
    { code: "ESP", label: "ESP - Spain Pesetas" },
    { code: "LKR", label: "LKR - Sri Lanka Rupees" },
    { code: "SDD", label: "SDD - Sudan Dinars" },
    { code: "SEK", label: "SEK - Sweden Kronor" },
    { code: "CHF", label: "CHF - Switzerland Francs" },
    { code: "TWD", label: "TWD - Taiwan New Dollars" },
    { code: "THB", label: "THB - Thailand Baht" },
    { code: "TTD", label: "TTD - Trinidad and Tobago Dollars" },
    { code: "TND", label: "TND - Tunisia Dinars" },
    { code: "TRY", label: "TRY - Turkey New Lira" },
    { code: "AED", label: "AED - United Arab Emirates Dirhams" },
    { code: "GBP", label: "GBP - United Kingdom Pounds" },
    { code: "USD", label: "USD - United States Dollars" },
    { code: "VEB", label: "VEB - Venezuela Bolivares" },
    { code: "VND", label: "VND- Vietnam Dong" },
    { code: "ZMK", label: "ZMK - Zambia Kwacha" },
  ],
  integration: {
    gmail: "gmail",
    calendar: "calendar",
    googleCalendar: "googleCalendar",
  },
  phoneNumberPossibleArrays: [
    "mobile_number",
    "phone_number",
    "fax_number",
    "cell_number",
    "contact_number",
    "telephone_number",
    "tele_number",
    "cell_phone",
    "home_phone",
  ],
  mailPossibleArrays: [
    "secondary_email",
    "primary_contact_email",
    "email",
    "primary_email",
    "secondary_contact_email",
  ],
  emailScheduleSampleData: {
    attachments: [],
    bcc: [],
    bodyContent: "",
    cc: [],
    companyIds: null,
    contactIds: null,
    createdAt: "",
    dealIds: null,
    emailSchedule: {
      createdAt: "",
      id: "",
      isActive: false,
      isDeleted: false,
      scheduleDateTime: "",
      scheduleSent: false,
      scheduleTimeZone: [],
      scheduledUTCDateTime: null,
      sentBy: "",
      updatedAt: "",
    },
    fieldIds: null,
    from: "",
    id: "",
    isActive: false,
    isDeleted: false,
    isSchedule: true,
    leadIds: null,
    linkClicked: false,
    linkOpened: null,
    mailClicked: false,
    mailOpened: null,
    subject: "",
    templateId: null,
    thread_id: "",
    to: [],
    updatedAt: "",
  },
  environmentRoute: "http://localhost:5200/crm",
  loginBaseUrl: "https://testin-accounts.cloudmaxis.com",
  commonHeader: {
    Accept: "application/json",
    "Content-Type": "application/json",
  },
  unAuthorizedErrorCode: 1700021,
};

export const AccessTokenRevokeMessage = "Access Token has been revoked";
