export const RegexPattern = {
	workspace: /^[a-zA-Z0-9 ]*$/,
	lowerCase: /^(?=.*[a-z])/,
	upperCase: /^(?=.*[A-Z])/,
	number: /^(?=.*[0-9])/,
	onlyNumbers: /(^100(%)?([.]0{1,2})?)$|(^\d{1,2}([.]\d{1,2})?)(%)?$/i,
	specialChar: /^(?=.*[!@#$%^&*])/,
	numberAndSpecialChar: /^(?=.*[0-9])(?=.*[@!()#$%^&+=]).*$/,
	upperAndLowerCase: /^(?=.*[a-z])(?=.*[A-Z])/,
	passwordStrength: /^(?=.{8,})/,
	nameRegexPattern: /^(?=.*[a-zA-Z])[a-zA-Z\s]+$/,
	minMaxCharacters: /^.{1,25}$/,
	roleName: /^[a-zA-Z ]*$/,
	roleNameMinMax: /^.{2,40}$/,
	groupNameMinMax: /^.{2,50}$/,
	filterNameMinMax: /^.{2,64}$/,
	email: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,})+$/,
	checkNumbers: /^[-+]?[0-9]\d*(\.\d+)?$/,
	numbersWithPercentage: /^(-?\d+|\d+[.]\d+)%?$/,
	urlChecker: /[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/,
	internalNameRegex: /^[a-z0-9_]*$/,
	stageName: /^[A-Za-z0-9\s\_]{1,40}$/,
	titleMinMax: /^.{2,100}$/,
	descriptionMinMax: /^[\s\S]{2,255}$/,
	isoDatePatternRegex: /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z/,
	fileNamePattern: /^[a-zA-Z0-9_.-\s]+$/,
	startWithAlphabet: /^[a-zA-Z]{1}/,
	numberOnly: /^[0-9]*$/,
	alphaNumeric: /^[a-zA-Z0-9_\s]*$/,
	removeHtmlTags: /(<([^>]+)>)/gi,
	websiteRegex:
		/^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:[/?#]\S*)?$/i,
	emailValidation: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,})+$/,
	phoneNumberRegex: /^\+?[1-9][0-9]{5,14}$/,
	currencyFormat: /^(\d){0,16}$/,
	currencyFormatDecimal: /^(\d){0,16}\.(\d){0,2}$/,
	numberWithSpecialCharacters: /^[0-9&.+,_-]+$/,
	phoneNumberValidation: /^\+?\d{0,15}$/,
	numberFormatFractional: /^(\d)*\.?(\d)*$/,
	numberFormatPercentage: /^(^100(\.0{1,2})?$)|(^([1-9]([0-9])?|0)(\.[0-9]{0,2})?$)/,
	htmlTagRemove: /<(?:"[^"]*"['"]*|'[^']*'['"]*|[^'">])+>/g,
	spanRemove: /<span[^>]*>[^>]*<\/span>/g,
	singleQuoteregex: /(['])/,
	alphabetsOnly: /^[a-zA-Z ]*$/,
	alphanumericSpaceRegex: /^[a-zA-Z][a-zA-Z0-9 ]+$/,
};
