export const ErrorMessage = {
	alreadySignedIn: 'There is already a signed in user.',
	jwtExpired: 'jwt expired',
	notLogin: 'User must be logged in',
	notValidJwt: 'Not a valid JWT token',
	emailRequired: 'Email is required',
	emailInvalid: 'Enter a valid Email',
	passwordRequired: 'Password is required',
	passwordInvalid: 'Enter a valid password',
	invalidNewPassword:
		'Password must contain minimum of 8 characters, one UpperCase, one LowerCase, one Number and one Special character',
	invalidConfirmNewPassword: 'Confirm Password should be same as New Password',
	oldPasswordRequired: 'Old password is required',
	newPasswordRequired: 'New password is required',
	confirmNewPasswordRequired: 'Confirm password is required',
	phoneNumberRequired: 'Phone number is required',
	phoneNumberInvalid: 'Enter a valid phone number',
	verificationCode: 'Verification code required',
	verificationCodeInvalid: 'Enter a valid verification code ',
	firstNameRequired: 'First name is required',
	lastNameRequired: 'Last name is required',
	orgRequired: 'Organisation is required',
	boardRequired: 'Board name is required',
	dateRangeRequired: 'Date range required',
	boardDescriptionRequired: 'Board description is required',
	maxCharactersExceeded: 'The characters must not exceed 64 characters',
	invalidURL: 'URL is invalid',
	validNumber: 'The value should only contain numbers',
	validPercentage: 'Please enter a percentage value between 0 and 100.',
	validCurrency: 'Please enter a valid number with up to two decimal places.',
	fieldNameRequired: 'Field name is required',
	dateFormatRequired: 'Date format is required',
	timeFormatRequired: 'Time format is required',
	weekStartRequired: 'Week start on is required',
	teamNameRequired: 'Team name is required',
	boardNameRequired: 'Board name is required',
	emailDuplicate: "You've entered the same email address twice.",
	unableToInvite: 'Unable to invite yourself',
};
